# Generated by Django 2.2.3 on 2019-07-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Venue', models.CharField(max_length=255)),
                ('LikedArtists', models.CharField(max_length=255)),
            ],
        ),
    ]
