# Generated by Django 2.2.2 on 2019-07-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Event',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='LikedArtists',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='Venue',
        ),
        migrations.AddField(
            model_name='matches',
            name='date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='matches',
            name='event',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matches',
            name='likedArtists',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matches',
            name='picLinks',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matches',
            name='venue',
            field=models.CharField(default='', max_length=255),
        ),
    ]
