# Generated by Django 2.2.2 on 2019-07-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190715_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
